# Generated by Django 3.1 on 2020-09-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200918_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Unique_id',
            field=models.CharField(default='sEwIKB', editable=False, max_length=6),
        ),
    ]
